# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setmember',
            name='VersionNumber',
        ),
        migrations.AddField(
            model_name='set',
            name='VersionNumber',
            field=models.IntegerField(default=0),
        ),
    ]
