# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170807_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordFuzzyMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FuzzyMatched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuzzymatched_record_set', to='app.Record')),
                ('ToMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomatch_record_set', to='app.Record')),
            ],
        ),
    ]
