# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recordfuzzymatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLFoundExtraSetMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewedStatus', models.IntegerField()),
                ('CorrespondingRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlset_record', to='app.Record')),
                ('CorrespondingSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlset_member', to='app.Set')),
            ],
        ),
    ]
