class ColoredRecord():

    def __init__(self):
        self.id = 0
        self.EnterpriseId = ""
        self.LastName = ""
        self.FirstName = ""
        self.MiddleName = ""
        self.Suffix = ""
        self.DOB = ""
        self.Gender = ""
        self.SSN = ""
        self.Address1 = ""
        self.Address2 = ""
        self.Zip = ""
        self.MothersMaidenName = ""
        self.MRN = ""
        self.City = ""
        self.State = ""
        self.Phone = ""
        self.Phone2 = ""
        self.Email = ""
        self.Alias = ""

        self.LastNameColor = ""
        self.FirstNameColor = ""
        self.MiddleNameColor = ""
        self.SuffixColor = ""
        self.DOBColor = ""
        self.GenderColor = ""
        self.SSNColor = ""
        self.Address1Color = ""
        self.Address2Color = ""
        self.ZipColor = ""
        self.MothersMaidenNameColor = ""
        self.MRNColor = ""
        self.CityColor = ""
        self.StateColor = ""
        self.PhoneColor = ""
        self.Phone2Color = ""
        self.EmailColor = ""
        self.AliasColor = ""
